# Generated by Django 6.0.4 on 2026-04-18 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AddField(
            model_name='article',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('World', 'World'), ('Tech', 'Tech'), ('Sports', 'Sports'), ('Health', 'Health'), ('Business', 'Business')], default='World', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='paraphrased_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
