# Generated by Django 6.0.4 on 2026-04-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_options_remove_article_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
